In [1]:
# Week 18 HomeWork Burhan Kabdayi

In [3]:
import numpy as np
import pandas as pd

In [4]:
np.random.seed(42)

In [ ]:
#1-Explain the difference between a vector and matrix in NumPy in one sentence.
Vector is one dimension which is only one row or list. Matrix is a two dimensions which includes row and column. 

In [ ]:
# 2 - Construct a NumPy Array from a list of 10 elements.

In [5]:
my_array = np.array(range(10))

In [6]:
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 3 -Construct a 10x10 matrix filled with '0's of the integer data type.

In [7]:
matrix = np.zeros((10, 10), dtype=int)
print(matrix)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [ ]:
#4- Construct a 10x10 matrix filled with '1's, data type float.

In [8]:
matrix1 = np.ones((10, 10), dtype=float)
print(matrix1)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
#5- Construct a 10x10 matrix filled with '9's of the integer data type.

In [10]:
matrix2 = np.ones((10, 10), dtype=int)*9
print(matrix2)

[[9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]]


In [ ]:
#6- Construct a one-dimensional array with values between 5 and 25 that jumps with steps of 3 ([5, 8, ...])

In [13]:
array1 = np.arange(5, 26, 3)
print(array1)

[ 5  8 11 14 17 20 23]


In [ ]:
#7-Create an array of size 30 with evenly spaced values between -1 and 1.

In [14]:
array2 = np.linspace(-1, 1, 30)
print(array2)

[-1.         -0.93103448 -0.86206897 -0.79310345 -0.72413793 -0.65517241
 -0.5862069  -0.51724138 -0.44827586 -0.37931034 -0.31034483 -0.24137931
 -0.17241379 -0.10344828 -0.03448276  0.03448276  0.10344828  0.17241379
  0.24137931  0.31034483  0.37931034  0.44827586  0.51724138  0.5862069
  0.65517241  0.72413793  0.79310345  0.86206897  0.93103448  1.        ]


In [ ]:
#8- Construct a 5x6 matrix with integers from 0 to 30.


In [16]:
matrix = np.arange(30).reshape((5, 6))
print(matrix)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [ ]:
#9- Create an array of 30 random integers and sort it in ascending order.


In [19]:
my_array = np.random.randint(100, size=30) 
sorted_array = np.sort(my_array)

In [20]:
print(sorted_array)

[ 1  1  2 14 20 20 21 21 23 29 32 37 48 51 52 57 59 60 63 71 74 74 75 82
 86 87 87 88 92 99]


In [ ]:
# 10- Construct a 5x10 matrix filled with the value 1 at each location. Print the following details about this matrix:


In [21]:
matrix = np.ones((5, 10), dtype=int)

print(matrix)
print("Shape of the matrix:", matrix.shape)
print("Data type of the elements:", matrix.dtype)
print("Total number of elements:", matrix.size)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]
Shape of the matrix: (5, 10)
Data type of the elements: int32
Total number of elements: 50


In [ ]:
# 11- Construct a 3x4x7 matrix with random integer values between 0 and 10 (a 3D matrix will be created).

In [22]:
matrix_3d = np.random.randint(0, 11, size=(3, 4, 7))
print(matrix_3d)

[[[10 10  9  2  6  3  8]
  [ 2  4  2  6  4  8  6]
  [ 1  3  8  1  9  8  9]
  [ 4  1  3  6  7  2  0]]

 [[ 3  1  7  3  1  5  5]
  [ 9  3  5  1  9  1  9]
  [ 3  7  6  8  7  4  1]
  [ 4  7  9  8  8  0  8]]

 [[ 6  8  7  0  7  7 10]
  [ 2  0  7  2  2  0 10]
  [ 4  9  6  9  8  6  8]
  [ 7  1  0  6  6  7  4]]]


In [ ]:
#12- Create an array of 20 random integers and reshape it into a 4x5 matrix.

In [24]:
array = np.random.randint(0, 100, size=20)
matrix = array.reshape((4, 5))

print(matrix)

[[76 50 62 95 51]
 [95  3 93 22 14]
 [42 28 35 12 31]
 [70 58 85 27 65]]


In [ ]:
#13- Construct a one-dimensional array by concetanating 4 separate one-dimensional arrays.

In [25]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])
d = np.array([10, 11, 12])

result = np.concatenate((a, b, c, d))

print(result)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
#14- Create a vector of length 3 (3x1) and a matrix of size 3x3. Combine these two arrays on a column-by-column basis using numpy methods.

In [26]:
a = np.array([1, 2, 3]).reshape(-1, 1)
b = np.random.randint(0, 10, (3, 3))

In [27]:
a

array([[1],
       [2],
       [3]])

In [28]:
b

array([[9, 8, 4],
       [5, 3, 9],
       [6, 8, 6]])

In [ ]:
# 15- What is the difference between "axis=1" and "axis=0" in Numpy functions?


In [ ]:
# Axis=1 means the column of a matrix, Axis = 0 means the row of the matrix

In [ ]:
# 16 - Create a random 1D vector with 20 elements. Find the 3rd, 5th and 7th elements of this vector.

In [29]:
vec = np.random.randint(0, 100, 20)
print("Vector:\n", vec)

third = vec[2]
fifth = vec[4]
seventh = vec[6]

print("Third element:", third)
print("Fifth element:", fifth)
print("Seventh element:", seventh)

Vector:
 [61 96  0 26 61 76  2 69 71 26  8 61 36 96 50 43 23 78 58 31]
Third element: 0
Fifth element: 61
Seventh element: 2


In [ ]:
#17 - Create a random vector with 10 elements and replace the 4th element of this array with a different number.


In [30]:
vec = np.random.rand(10)
print("Vector before replacement:\n", vec)
vec[3] = 0.5
print("Vector after replacement:\n", vec)

Vector before replacement:
 [0.51879062 0.70301896 0.3636296  0.97178208 0.96244729 0.2517823
 0.49724851 0.30087831 0.28484049 0.03688695]
Vector after replacement:
 [0.51879062 0.70301896 0.3636296  0.5        0.96244729 0.2517823
 0.49724851 0.30087831 0.28484049 0.03688695]
